AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Role and Policy for Secrets Manager Access

Parameters:
  AWSRegion:
    Type: String
    Description: "AWS Region"
  AWSAccountId:
    Type: String
    Description: "AWS account ID"

Resources:
  SecretManagerCrudRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Secret_Manager_CRUD_Access_Role_For_Skyu
      Description: Secret Manager CRUD Access Role for Skyu
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::678356101643:root" # Skyu-dev-v2 acc id
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Secret_Manager_CRUD_Access_Policy_For_Skyu
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - secretsmanager:GetRandomPassword
                  - secretsmanager:ListSecrets
                Resource: "*"
              - Sid: VisualEditor1
                Effect: Allow
                Action: secretsmanager:*
                Resource:
                  - Fn::Sub: "arn:aws:secretsmanager:${AWSRegion}:${AWSAccountId}:secret:*"

Outputs:
  SecretManagerCrudRoleArn:
    Description: ARN of the Secrets Manager CRUD role
    Value:
      Fn::GetAtt:
        - SecretManagerCrudRole
        - Arn
