package constants

var SHARED_FLOW = "SHARED"
var PRIVATE_FLOW = "PRIVATE"
var ACCEPTED_FLOWS = [2]string{SHARED_FLOW, PRIVATE_FLOW}

var CREDENTIALS_SCOPE = "CREDENTIALS"
var CONFIGS_SCOPE = "CONFIGS"
var OTHERS_SCOPE = "OTHERS"
var ACCEPTED_SCOPES = [3]string{CREDENTIALS_SCOPE, CONFIGS_SCOPE, OTHERS_SCOPE}

var FLOW_META_DATA = "Flow"
var ARN_META_DATA = "ARN"
var REGION_META_DATA = "Region"
var PROVIDER_META_DATA = "Provider"
var SECRET_META_DATA = "Secret"
